INSERT INTO airline(code, name) VALUES('9E', 'Endeavor Air Inc.');
INSERT INTO airline(code, name) VALUES('AA', 'American Airlines Inc.');
INSERT INTO airline(code, name) VALUES('AS', 'Alaska Airlines Inc.');
INSERT INTO airline(code, name) VALUES('AX', 'Trans States Airlines');
INSERT INTO airline(code, name) VALUES('B6', 'JetBlue Airways');
INSERT INTO airline(code, name) VALUES('C5', 'Commutair Aka Champlain Enterprises, Inc.');
INSERT INTO airline(code, name) VALUES('CP', 'Compass Airlines');
INSERT INTO airline(code, name) VALUES('DL', 'Delta Air Lines Inc.');
INSERT INTO airline(code, name) VALUES('EM', 'Empire Airlines Inc.');
INSERT INTO airline(code, name) VALUES('EV', 'ExpressJet Airlines Inc.');
INSERT INTO airline(code, name) VALUES('F9', 'Frontier Airlines Inc.');
INSERT INTO airline(code, name) VALUES('G4', 'Allegiant Air');
INSERT INTO airline(code, name) VALUES('G7', 'GoJet Airlines, LLC d/b/a United Express');
INSERT INTO airline(code, name) VALUES('HA', 'Hawaiian Airlines Inc.');
INSERT INTO airline(code, name) VALUES('KS', 'Peninsula Airways Inc.');
INSERT INTO airline(code, name) VALUES('MQ', 'Envoy Air');
INSERT INTO airline(code, name) VALUES('NK', 'Spirit Air Lines');
INSERT INTO airline(code, name) VALUES('OH', 'Comair Inc.');
INSERT INTO airline(code, name) VALUES('OO', 'SkyWest Airlines Inc.');
INSERT INTO airline(code, name) VALUES('PT', 'Capital Cargo International');
INSERT INTO airline(code, name) VALUES('QX', 'Horizon Air');
INSERT INTO airline(code, name) VALUES('UA', 'United Air Lines Inc.');
INSERT INTO airline(code, name) VALUES('VX', 'Virgin America');
INSERT INTO airline(code, name) VALUES('WN', 'Southwest Airlines Co.');
INSERT INTO airline(code, name) VALUES('YV', 'Mesa Airlines Inc.');
INSERT INTO airline(code, name) VALUES('YX', 'Republic Airlines');
INSERT INTO airline(code, name) VALUES('ZW', 'Air Wisconsin Airlines Corp');
