INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ABE', 'Allentown Lehigh Valley International Airport', '리하이 밸리 국제공항', 40.65236, -75.4404, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ABI', 'Abilene Regional Airport', '애빌린 지역 공항', 32.41132, -99.6819, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ABQ', 'Albuquerque International Sunport Airport', '앨버커키 국제 선포트 공항', 35.04022, -106.60919, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ABR', 'Aberdeen Regional Airport', '애버딘 지역 공항', 45.44906, -98.42183, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ABY', 'Southwest Georgia Regional Airport', '사우스웨스트 조지아 지역 공항', 31.53552, -84.19447, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ACK', 'Nantucket Memorial Airport', '낸터컷 메모리얼 공항', 41.25305, -70.06018, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ACT', 'Waco Regional Airport', '웨이코 지역 공항', 31.61129, -97.23052, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ACV', 'Arcata-Eureka Airport', '아르카타-유레카 공항', 40.97812, -124.10862, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ACY', 'Atlantic City International Airport', '애틀랜틱시티 국제공항', 39.45758, -74.57717, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ADK', 'Adak Island Naval Airport', '아다크 섬 해군 공항', 51.87796, -176.64603, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ADQ', 'Kodiak Benny Benson State Airport', '코디악 공항', 57.74997, -152.49386, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AEX', 'Alexandria International Airport', '알렉산드리아 국제공항', 31.32737, -92.54856, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AGS', 'Augusta Regional Airport', '오거스타 공항앳 부시 필드', 33.36996, -81.9645, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AKN', 'King Salmon Airport', '킹 새먼 공항', 58.6768, -156.64922, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ALB', 'Albany International Airport', '올버니 국제공항', 42.74812, -73.80298, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ALO', 'Waterloo Regional Airport', '워털루 공항', 42.55708, -92.40034, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ALS', 'San Luis Valley Regional Airport', '샌루이스밸리 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ALW', 'Walla Walla Regional Airport', '왈라왈라 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AMA', 'Rick Husband Amarillo International Airport', '릭 허드슨 애머릴로 국제공항', 35.21937, -101.70593, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ANC', 'Ted Stevens Anchorage International Airport', '테드 스티븐스 앵커리지 국제공항', 61.17432, -149.99619, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('APN', 'Alpena County Regional Airport', '앨피너 카운티 공항', 45.07807, -83.56029, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ART', 'Watertown International Airport', '워터타운 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ASE', 'Aspen/Pitkin County Airport', '아스펜 핏킨 카운티 공항', 39.22316, -106.86885, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ATL', 'Atlanta Hartsfield-Jackson International Airport', '하츠필드 잭슨 애틀랜타 국제공항', 33.64044, -84.42694, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ATW', 'Appleton International Airport', '애플턴 국제공항', 44.25741, -88.51948, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ATY', 'Watertown Airport', '워터타운 지역공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AUS', 'Austin-Bergstrom International Airport', '오스틴 버그스트롬 국제공항', 30.19453, -97.66987, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AVL', 'Asheville Regional Airport', '애슈빌 공항', 35.43619, -82.54181, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AVP', 'Wilkes-Barre/Scranton International Airport', '윌크스배러/스크랜턴 국제공항', 41.33815, -75.72427, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AZA', 'Phoenix Mesa Gateway Airport', '피닉스메사 게이트웨이 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('AZO', 'Kalamazoo Battle Creek International Airport', '캘러머주/배틀크릭 국제공항', 42.23488, -85.55206, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BDL', 'Hartford Bradley International Airport', '브래들리 국제공항', 41.93887, -72.68323, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BET', 'Bethel Airport', '베델 공항', 60.77978, -161.838, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BFF', 'Scottsbluff Western Nebraska Regional Airport', '웨스턴 네브래스카 리저널 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BFL', 'Bakersfield Meadows Field Airport', '메도우즈 필드 공항', 35.4336, -119.05677, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BFM', 'Mobile International Airport', '모빌 다운타운 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BGM', 'Greater Binghamton Airport', '그레이터 빙엄턴 공항', 42.20848, -75.97961, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BGR', 'Bangor International Airport', '뱅거 국제공항', 44.80744, -68.82814, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BHM', 'Birmingham-Shuttlesworth International Airport', '버밍엄 셔틀스워스 국제공항', 33.56294, -86.75355, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BIH', 'Bishop Regional Airport', '이스턴 시에라 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BIL', 'Billings Logan International Airport', '빌링스 로건 국제공항', 45.80766, -108.54286, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BIS', 'Bismarck Airport', '비스마르크 공항', 46.77411, -100.74672, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BJI', 'Bemidji Regional Airport', '베미지 지역공항', 47.50942, -94.93372, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BKG', 'Branson Airport', '브랜슨 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BLI', 'Bellingham International Airport', '벨링햄 국제공항', 48.79275, -122.53753, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BLV', 'St Louis MidAmerica Airport', '미드아메리카 세인트루이스 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BMI', 'Bloomington Central Illinois Regional Airport', '센트럴 일리노이 공항', 40.47799, -88.91595, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BNA', 'Nashville International Airport', '내슈빌 국제공항', 36.12448, -86.67818, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BOI', 'Boise Airport', '보이시 공항', 43.56444, -116.22278, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BOS', 'Boston Logan International Airport', '로건 국제공항', 42.36435, -71.00518, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BPT', 'Jack Brooks Regional Airport', '잭 브룩스 공항', 29.95083, -94.02069, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BQK', 'Brunswick Golden Isles Airport', '브런즈윅 골든 아일즈 공항', 31.25903, -81.46631, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BRD', 'Brainerd Lakes Regional Airport', '브레이너드 레이크 공항', 46.39786, -94.13723, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BRO', 'Brownsville South Padre Island International Airport', '사우스 파드레 아일랜드 국제공항', 25.90683, -97.42586, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BRW', 'Barrow Wiley Post/Will Rogers Memorial Airport', '와일리 포스트 윌 로저스 메모리얼 공항', 71.28545, -156.766, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BTM', 'Butte Bert Mooney Airport', '버트 무니 공항', 45.9548, -112.49746, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BTR', 'Baton Rouge Metropolitan Airport', '배턴루지 메트로폴리탄 공항', 30.53316, -91.14963, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BTV', 'Burlington International Airport', '벌링턴 국제공항', 44.473, -73.15031, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BUF', 'Buffalo Niagara International Airport', '버팔로 나이아가라 국제공항', 42.94052, -78.73217, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BUR', 'Hollywood Burbank Airport', '밥 호프 공항', 34.20062, -118.3585, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BWI', 'Baltimore/Washington International Airport', '볼티모어/워싱턴 인터내셔널 서굿 마샬 공항', 39.1754, -76.6682, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('BZN', 'Bozeman Yellowstone International Airport', '보즈먼 옐로스톤 국제공항', 45.7769, -111.15301, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CAE', 'Columbia Metropolitan Airport', '콜럼비아 메트로폴리탄 공항', 33.93884, -81.11954, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CAK', 'Akron-Canton Airport', '애크런 캔턴 공항', 40.91631, -81.44247, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CDB', 'Cold Bay Airport', '콜드 베이 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CDC', 'Cedar City Regional Airport', '시더 시티 공항', 37.70097, -113.09858, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CDV', 'Cordova Mudhole Smith Airport', '멀 K. 스미스 공항', 60.49183, -145.47765, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CGI', 'Cape Girardeau Regional Airport', '케이프 지라도 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CHA', 'Chattanooga Metropolitan Airport', '채터누가 메트로폴피탄 공항', 35.03527, -85.20379, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CHO', 'Charlottesville Albemarle Airport', '샬러츠빌 앨버말 공항', 38.13864, -78.45286, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CHS', 'Charleston International Airport', '찰스턴 국제공항', 32.89865, -80.04051, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CID', 'Cedar Rapids Eastern Iowa Airport', '이스턴 아이오와 공항', 41.88459, -91.71087, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CIU', 'Chippewa County International Airport', '치페와 카운티 국제공항', 46.25075, -84.47239, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CKB', 'North Central West Virginia Airport', '노스 센트럴 웨스트 버지니아 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CLE', 'Cleveland Hopkins International Airport', '클리블랜드 홉킨스 국제공항', 41.41089, -81.8494, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CLL', 'Easterwood Airport', '이스터우드 공항', 30.58859, -96.36382, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CLT', 'Charlotte Douglas International Airport', '샬럿 더글러스 국제공항', 35.21401, -80.94313, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CMH', 'John Glenn Columbus International Airport', '존 글렌 콜럼버스 국제공항', 39.99799, -82.89188, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CMI', 'University of Illinois - Willard Airport', '일리노이 대학교 윌러드 공항', 40.03925, -88.27806, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CMX', 'Hancock Houghton County Memorial Airport', '휴튼 카운티 메모리얼 공항', 47.16842, -88.48906, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CNY', 'Moab Canyonlands Field', '캐니언랜즈 필드', 38.75496, -109.75484, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('COD', 'Cody Yellowstone Regional Airport', '옐로스톤 공항', 44.52019, -109.0238, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('COS', 'Colorado Springs Airport', '콜로라도 스프링스 공항', 38.80581, -104.70025, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('COU', 'Columbia Regional Airport', '콜럼비아 공항', 38.81809, -92.21963, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CPR', 'Casper/Natrona County International Airport', '캐스퍼 내트로나 카운티 국제공항', 42.90836, -106.46447, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CRP', 'Corpus Christi International Airport', '코퍼스 크리스티 국제공항', 27.77036, -97.50122, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CRW', 'West Virginia International Yeager Airport', '예거 공항', 38.37315, -81.59319, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CSG', 'Columbus Airport', '콜럼버스 공항', 32.51633, -84.93886, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CVG', 'Cincinnati/Northern Kentucky International Airport', '신시내티/노던 켄터키 국제공항', 39.04614, -84.66217, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CWA', 'Central Wisconsin Airport', '센트럴 위스콘신 공항', 44.77762, -89.66678, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('CYS', 'Cheyenne Regional Airport', '샤이엔 지역공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DAB', 'Daytona Beach International Airport', '데이토나 비치 국제공항', 29.17992, -81.05806, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DAL', 'Dallas Love Field', '댈러스 러브 필드', 32.84711, -96.85177, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DAY', 'Dayton International Airport', '데이턴 국제공항', 39.90238, -84.21938, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DBQ', 'Dubuque Regional Airport', '더뷰크 공항', 42.40296, -90.70917, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DDC', 'Dodge City Regional Airport', '닷지 시티 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DEC', 'Decatur Airport', '디케 이터 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DEN', 'Denver International Airport', '덴버 국제공항', 39.85841, -104.667, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DFW', 'Dallas Fort Worth International Airport', '댈러스/포트워스 국제공항', 32.89595, -97.0372, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DHN', 'Dothan Regional Airport', '도탄 공항', 31.32134, -85.44963, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DIK', 'Dickinson Theodore Roosevelt Regional Airport', '디킨슨 시어도어 루즈벨트 공항', 46.79739, -102.80195, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DLG', 'Dillingham Airport', '딜링햄 공항', 59.04541, -158.50334, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DLH', 'Duluth International Airport', '덜루스 국제공항', 46.84209, -92.19365, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DRO', 'Durango-La Plata County Airport', '두랑고 라플라타 카운티 공항', 37.15152, -107.75377, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DRT', 'Del Rio International Airport', '델 리오 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DSM', 'Des Moines International Airport', '디모인 국제공항', 41.53493, -93.66068, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DTW', 'Detroit Metropolitan Airport', '디트로이트 메트로폴리탄 웨인 카운티 공항', 42.21206, -83.34884, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DUT', 'Dutch Harbor Emergency Field', '어널래스카 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('DVL', 'Devils Lake Regional Airport', '데블스 레이크 리저널 공항', 48.11425, -98.90878, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EAR', 'Kearney Regional Airport', '카니 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EAT', 'Pangborn Memorial Airport', '팽본 메모리얼 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EAU', 'Chippewa Valley Regional Airport', '치페와 밸리 공항', 44.86526, -91.48507, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ECP', 'Panama City Northwest Florida Beaches International Airport', '노스웨스트 플로리다 비치 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EGE', 'Vail Eagle County Regional Airport', '이글 카운티 공항', 39.64257, -106.9177, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EKO', 'Elko Regional Airport', '엘코 공항', 40.82493, -115.7917, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ELM', 'Elmira Corning Regional Airport', '엘미라 코닝 지역 공항', 42.15991, -76.89144, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ELP', 'El Paso International Airport', '엘패소 국제공항', 31.80667, -106.37781, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ERI', 'Erie International Airport', '이리 국제공항', 42.08202, -80.17622, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ESC', 'Delta County Airport', '델타 카운티 공항', 45.72267, -87.09373, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EUG', 'Eugene Airport', '유진 공항', 44.12326, -123.21869, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EVV', 'Evansville Regional Airport', '에반스빌 공항', 38.03799, -87.53063, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EWN', 'New Bern Coastal Carolina Regional Airport', '코스탈 캐롤라이나 공항', 35.07297, -77.04294, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EWR', 'New York Newark Liberty International Airport', '뉴어크 리버티 국제공항', 40.6925, -74.16866, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('EYW', 'Key West International Airport', '키웨스트 국제공항', 24.55611, -81.75956, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FAI', 'Fairbanks International Airport', '페어뱅크스 국제공항', 64.81368, -147.85967, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FAR', 'Fargo Hector International Airport', '헥터 국제공항', 46.91935, -96.81499, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FAT', 'Fresno Yosemite International Airport', '프레즈노 요세미티 국제공항', 36.77619, -119.71814, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FAY', 'Fayetteville Regional Airport', '페이엇빌 리저널 공항', 34.99147, -78.88, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FCA', 'Kalispell Glacier Park International Airport', '글레이셔 파크 국제공항', 48.3114, -114.25507, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FLG', 'Grand Canyon Pulliam Airport', '플래그스태프 풀리엄 공항', 35.13845, -111.67122, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FLL', 'Fort Lauderdale-Hollywood International Airport', '포트로더데일 할리우드 국제공항', 26.07258, -80.15275, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FLO', 'Florence Regional Airport', '피렌체 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FNT', 'Flint Bishop International Airport', '비숍 국제공항', 42.9655, -83.74346, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FOD', 'Fort Dodge Regional Airport', '포트닷지 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FSD', 'Sioux Falls Regional Airport', '수폴스 지역공항', 43.58135, -96.7417, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FSM', 'Fort Smith Regional Airport', '포트 스미스 공항', 35.33659, -94.36744, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('FWA', 'Fort Wayne International Airport', '포트 웨인 국제공항', 40.97847, -85.19515, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GCC', 'Northeast Wyoming Regional Airport', '질레트 캠벨 카운티 공항', 44.3489, -105.53936, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GCK', 'Garden City Regional Airport', '가든 시티 공항', 37.92752, -100.72441, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GEG', 'Spokane International Airport', '스포캔 국제공항', 47.61986, -117.53384, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GFK', 'Grand Forks International Airport', '그랜드 폭스 국제공항', 47.94926, -97.17611, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GGG', 'East Texas Regional Airport', '이스트 텍사스 공항', 32.38486, -94.71171, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GJT', 'Grand Junction Regional Airport', '워커 필드 공항', 39.12241, -108.52673, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GNV', 'Gainesville Regional Airport', '게인즈빌 공항', 29.69006, -82.27178, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GPT', 'Gulfport-Biloxi International Airport', '걸프포트 빌럭시 국제공항', 30.40728, -89.07009, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GRB', 'Green Bay Austin Straubel International Airport', '오스틴 스트라우벨 국제공항', 44.48507, -88.12959, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GRI', 'Central Nebraska Regional Airport', '센트럴 네브래스카 공항', 40.96747, -98.30861, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GRK', 'Killeen/Fort Hood Regional Airport', '킬린 포트 후드 공항', 31.0649, -97.8278, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GRR', 'Grand Rapids Gerald R Ford International Airport', '제럴드 R. 포드 국제공항', 42.88082, -85.52277, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GSO', 'Piedmont Triad International Airport', '피드몬트 트라이어드 국제공항', 36.09775, -79.9373, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GSP', 'Greenville-Spartanburg International Airport', '그린빌 스파르탄버그 국제공항', 34.89567, -82.21886, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GST', 'Gustavus Airport', '구스타프 공항', 58.42438, -135.70738, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GTF', 'Great Falls International Airport', '그레이트 폴스 국제공항', 47.482, -111.37069, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GTR', 'Golden Triangle Regional Airport', '골든 트라이앵글 공항', 33.45033, -88.59137, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('GUC', 'Gunnison Crested Butte Regional Airport', '거니슨 크레스티드 뷰트 공항', 38.53396, -106.93318, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HDN', 'Yampa Valley Regional Airport', '얌파 밸리 공항', 40.48118, -107.21766, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HGR', 'Hagerstown Regional Airport', '헤이거즈타운 지역공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HHH', 'Hilton Head Island Airport', '힐튼 헤드 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HIB', 'Range Regional Airport', '레인지 공항', 47.3866, -92.83899, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HLN', 'Helena Regional Airport', '헬레나 공항', 46.60682, -111.98275, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HNL', 'Honolulu Daniel K Inouye International Airport', '호놀룰루 국제공항', 21.31869, -157.92241, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HOB', 'Lea County Regional Airport', '레아 카운티 공항', 32.68753, -103.21703, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HOU', 'Houston William P. Hobby Airport', '윌리엄 P. 하비 공항', 29.64542, -95.27889, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HPN', 'Westchester County Airport', '웨스트체스터 카운티 공항', 41.06696, -73.70757, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HRL', 'Harlingen Valley International Airport', '밸리 국제공항', 26.22851, -97.65439, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HSV', 'Huntsville International Airport', '헌츠빌 국제공항', 34.64045, -86.77311, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HTS', 'Huntington Tri-State Airport', '트라이 스테이트 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HVN', 'Tweed New Haven Airport', '트위드 뉴 헤이븐 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HYA', 'Cape Cod Gateway Airport', '반스터블 뮤니시펄 공항', 41.66934, -70.28036, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('HYS', 'Hays Regional Airport', '헤이스 공항', 38.84494, -99.27403, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('IAD', 'Washington Dulles International Airport', '워싱턴 덜레스 국제공항', 38.94453, -77.45581, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('IAG', 'Niagara Falls International Airport', '나이아가라 폭포 국제공항', 43.10726, -78.94538, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('IAH', 'Houston George Bush Intercontinental Airport', '조지 부시 인터컨티넨털 공항', 29.98047, -95.33972, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ICT', 'Wichita Dwight D Eisenhower National Airport', '위치타 드와이트 D. 아이젠하워 내셔널 공항', 37.64996, -97.43305, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('IDA', 'Idaho Falls Regional Airport', '아이다호폴스 공항', 43.51456, -112.07017, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ILG', 'Wilmington New Castle Airport', '윌밍턴 공항', 39.67872, -75.60653, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ILM', 'Wilmington International Airport', '윌밍턴 국제공항', 34.27061, -77.90256, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('IMT', 'Iron Mountain Ford Airport', '포드 공항', 45.81835, -88.11454, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('IND', 'Indianapolis International Airport', '인디애나폴리스 국제공항', 39.71733, -86.29438, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('INL', 'Falls International Airport', '폴스 국제공항', 48.56619, -93.40307, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('IPT', 'Williamsport Regional Airport', '윌리엄스포트 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ISP', 'Long Island MacArthur Airport', '롱 아일랜드 맥아더 공항', 40.79524, -73.10021, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ITH', 'Ithaca Tompkins International Airport', '이타카 톰킨스 공항', 42.49103, -76.45844, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ITO', 'Hilo International Airport', '힐로 국제공항', 19.72026, -155.04847, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JAC', 'Jackson Hole Airport', '잭슨홀 공항', 43.60732, -110.73774, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JAN', 'Jackson-Medgar Wiley Evers International Airport', '잭슨 에버스 국제공항', 32.31117, -90.07589, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JAX', 'Jacksonville International Airport', '잭슨빌 국제공항', 30.49406, -81.68786, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JFK', 'New York John F Kennedy International Airport', '존 F. 케네디 국제공항', 40.63975, -73.77893, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JHM', 'Kapalua Airport', '카팔루아 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JLN', 'Joplin Regional Airport', '조플린 공항', 37.15181, -94.49827, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JMS', 'Jamestown Regional Airport', '제임스타운 공항', 46.92972, -98.6782, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JNU', 'Juneau International Airport', '주노 국제공항', 58.35496, -134.57628, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('JST', 'John Murtha Johnstown-Cambria County Airport', '존 머사 존스타운 캄브리아 카운티 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('KOA', 'Kona International Airport', '케아홀 코나 국제공항', 19.73877, -156.04563, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('KTN', 'Ketchikan International Airport', '케치칸 국제공항', 55.35557, -131.71374, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LAN', 'Lansing Capital Region International Airport', '캐피털 리전 국제공항', 42.7787, -84.58736, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LAR', 'Laramie Regional Airport', '래러미 공항', 41.31205, -105.67499, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LAS', 'Las Vegas Harry Reid International Airport', '해리 리드 국제공항', 36.08036, -115.15233, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LAW', 'Lawton/Fort Sill Regional Airport', '로턴 포트실 공항', 34.56771, -98.41664, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LAX', 'Los Angeles International Airport', '로스 앤젤레스 국제공항', 33.94254, -118.40807, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LBB', 'Lubbock Preston Smith International Airport', '러벅 프레스턴 스미스 국제공항', 33.66364, -101.82278, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LBE', 'Arnold Palmer Regional Airport', '아놀드 파머 공항', 40.27594, -79.4048, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LBF', 'North Platte Regional Airport', '노스플랫 지역공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LBL', 'Liberal Municipal Airport', '리버럴 미드 아메리카 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LCH', 'Lake Charles Regional Airport', '레이크 찰스 공항', 30.1261, -93.2234, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LCK', 'Columbus Rickenbacker International Airport', '리켄베커 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LEX', 'Lexington Blue Grass Airport', '블루 그래스 공항', 38.03697, -84.60539, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LFT', 'Lafayette Regional Airport', '라파예트 공항', 30.20528, -91.98766, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LGA', 'New York LaGuardia Airport', '라과디아 공항', 40.77724, -73.87261, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LGB', 'Long Beach Airport', '롱비치 공항', 33.81772, -118.15161, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LIH', 'Lihue Airport', '리후에 공항', 21.97598, -159.33896, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LIT', 'Little Rock Bill and Hillary Clinton National Airport', '클린턴 내셔널 공항', 34.7294, -92.22425, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LNK', 'Lincoln Airport', '링컨 공항', 40.85097, -96.75925, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LNY', 'Lanai Airport', '라나이 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LRD', 'Laredo International Airport', '라레도 국제공항', 27.54374, -99.46154, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LSE', 'La Crosse Regional Airport', '라크로스 공항', 43.87938, -91.25654, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LWB', 'Lewisburg Greenbrier Valley Airport', '그린브리어 밸리 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LWS', 'Lewiston Nez Perce County Regional Airport', '루이스턴 네즈 퍼스 카운티 공항', 46.3745, -117.01539, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('LYH', 'Lynchburg Regional Airport', '린치버그 리저널 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MAF', 'Midland International Airport', '미들랜드 국제 항공 우주 항구', 31.94253, -102.20191, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MBS', 'MBS International Airport', 'MBS 국제공항', 43.53291, -84.07965, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MCI', 'Kansas City International Airport', '캔자스시티 국제공항', 39.29761, -94.71391, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MCO', 'Orlando International Airport', '올랜도 국제공항', 28.42889, -81.31603, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MCW', 'Mason City Municipal Airport', '메이슨 시티 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MDT', 'Harrisburg International Airport', '해리스버그 국제공항', 40.1935, -76.7634, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MDW', 'Chicago Midway International Airport', '미드웨이 국제공항', 41.78598, -87.75242, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MEI', 'Meridian Regional Airport', '메리디언 지역공항', 32.33313, -88.75121, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MEM', 'Memphis International Airport', '멤피스 국제공항', 35.04242, -89.97667, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MFE', 'McAllen International Airport', '매캘런 밀러 국제공항', 26.17583, -98.23861, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MFR', 'Rogue Valley International-Medford Airport', '로그 밸리 국제-메드퍼드 공항', 42.37423, -122.8735, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MGM', 'Montgomery Regional Airport', '몽고메리 지역공항', 32.30064, -86.39398, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MHK', 'Manhattan Regional Airport', '맨해튼 공항', 39.14097, -96.67083, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MHT', 'Manchester-Boston Regional Airport', '맨체스터 보스턴 공항', 42.93452, -71.43706, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MIA', 'Miami International Airport', '마이애미 국제공항', 25.79325, -80.29056, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MKE', 'Milwaukee Mitchell International Airport', '밀워키 미첼 국제공항', 42.94722, -87.89658, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MKG', 'Muskegon County Airport', '머스키건 카운티 공항', 43.16949, -86.23822, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MKK', 'Molokai Airport', '몰로카이 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MLB', 'Melbourne Orlando(US) International Airport ', '멜버른 올랜도(US) 국제공항', 28.10275, -80.64581, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MLI', 'Quad Cities International Airport', '쿼드 시티 국제공항', 41.44853, -90.50754, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MLU', 'Monroe Regional Airport', '먼로 공항', 32.51087, -92.03769, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MMH', 'Mammoth Lakes Mammoth Yosemite Airport', '맘모스 요세미티 공항', 37.62405, -118.83777, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MOB', 'Mobile Regional Airport', '모빌 공항', 30.69142, -88.24283, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MOT', 'Minot International Airport', '미놋 국제공항', 48.25938, -101.28033, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MQT', 'Marquette Sawyer International Airport', '소여 국제공항', 46.35364, -87.39536, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MRY', 'Monterey Regional Airport', '몬터레이 공항', 36.58698, -121.84295, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MSN', 'Dane County Regional Airport', '데인 카운티 리저널 공항', 43.13986, -89.33751, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MSO', 'Missoula Montana Airport', '미줄라 국제공항', 46.91631, -114.09056, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MSP', 'Minneapolis St Paul International Airport', '미니애폴리스 세인트폴 국제공항', 44.88055, -93.21692, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MSY', 'New Orleans Louis Armstrong International Airport', '루이 암스트롱 뉴올리언스 국제공항', 29.99339, -90.25803, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MTJ', 'Montrose Regional Airport', '몬트로즈 공항', 38.50887, -107.89383, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MVY', 'Marthas Vineyard Airport', '마사스 빈야드 공항', 41.39303, -70.61433, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('MYR', 'Myrtle Beach International Airport', '머틀 비치 국제공항', 33.67975, -78.92833, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OAJ', 'Jacksonville Albert J Ellis Airport', '앨버트 J. 엘리스 공항', 34.82916, -77.61214, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OAK', 'Oakland San Francisco Bay Airport', '오클랜드 국제공항', 37.72129, -122.22072, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OGD', 'Ogden Regional Airport', '오그덴 힝클리 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OGG', 'Kahului Airport', '카훌루이 공항', 20.89865, -156.43046, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OGS', 'Ogdensburg International Airport', '오그덴스버그 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OKC', 'Will Rogers World Airport', '윌 로저스 월드 공항', 35.39309, -97.60073, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OMA', 'Omaha Eppley International Airport', '에플리 비행장', 41.30252, -95.89417, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OME', 'Nome Airport', '놈 공항', 64.5122, -165.44525, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ONT', 'Ontario International Airport', '온타리오 국제공항', 34.056, -117.60119, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ORD', 'Chicago OHare International Airport', '오헤어 국제공항', 41.9796, -87.90446, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ORF', 'Norfolk International Airport', '노퍽 국제공항', 36.89461, -76.20122, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ORH', 'Worcester Regional Airport', '우스터 공항', 42.26734, -71.87571, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OTH', 'Southwest Oregon Regional Airport', '사우스웨스트 오리건 공항', 43.41714, -124.24603, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OTZ', 'Kotzebue Airport', '랄프 빈 메모리얼 공항', 66.88468, -162.59855, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('OWB', 'Owensboro-Daviess County Regional Airport', '오웬스보로 데이비스 카운티 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PAE', 'Seattle Paine Field International Airport', '페인 필드 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PAH', 'Barkley Regional Airport', '바클리 공항', 37.06083, -88.77375, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PBG', 'Plattsburgh International Airport', '플래츠버그 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PBI', 'Palm Beach International Airport', '팜 비치 국제공항', 26.68316, -80.09559, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PDX', 'Portland International Airport', '포틀랜드 국제공항', 45.58872, -122.5975, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PGD', 'Punta Gorda Charlotte County Airport', '푼타고르다 샬럿카운티 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PGV', 'Pitt-Greenville Airport', '피트 그린빌 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PHF', 'Newport News Williamsburg International Airport', '뉴포트뉴스/윌리엄스버그 국제공항', 37.1319, -76.49299, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PHL', 'Philadelphia International Airport', '필라델피아 국제공항', 39.87195, -75.24114, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PHX', 'Phoenix Sky Harbor International Airport', '피닉스 스카이 하버 국제공항', 33.43417, -112.00806, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PIA', 'Peoria General Wayne A. Downing International Airport', '제너럴 웨인 A. 다우닝 피오리아 국제공항', 40.66424, -89.69331, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PIB', 'Hattiesburg-Laurel Regional Airport', '해티즈버그 로렐 공항', 31.46715, -89.33706, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PIE', 'Tampa St Pete-Clearwater International Airport', '세인트피트 클리어워터 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PIH', 'Pocatello Regional Airport', '포커텔로 공항', 42.91131, -112.59586, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PIR', 'Pierre Regional Airport', '피에르 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PIT', 'Pittsburgh International Airport', '피츠버그 국제공항', 40.49147, -80.23287, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PLN', 'Pellston Regional Airport', '펠스턴 리저널 공항', 45.57093, -84.79672, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PNS', 'Pensacola International Airport', '펜사콜라 국제공항', 30.47331, -87.18744, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PQI', 'Presque Isle International Airport', '프레스크 아일 노던 메인 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PRC', 'Prescott Regional Airport', '어니스트 에이 러브 필드', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PSC', 'Pasco Tri-Cities Airport', '트라이 시티 공항', 46.26468, -119.11903, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PSG', 'Petersburg James A Johnson Airport', '피터스버그 제임스 A. 존슨 공항', 56.80165, -132.94528, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PSM', 'Portsmouth Pease International Airport', '피스 포츠머스 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PSP', 'Palm Springs International Airport', '팜스프링스 국제공항', 33.82922, -116.50625, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PUB', 'Pueblo Airport', '푸에블로 메모리얼 공항', 38.28909, -104.49657, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PUW', 'Pullman Moscow Regional Airport', '풀만 모스크바 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PVD', 'Rhode Island T F Green International Airport', '시어도어 프랜시스 그린 스테이트 공항', 41.724, -71.42822, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PVU', 'Provo Municipal Airport', '프로보 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('PWM', 'Portland International Jetport', '포틀랜드 국제공항제트포트', 43.64617, -70.30875, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RAP', 'Rapid City Regional Airport', '래피드 시티 공항', 44.04532, -103.05737, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RDD', 'Redding Regional Airport', '레딩 공항', 40.50898, -122.2934, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RDM', 'Redmond Municipal Airport', '로버츠 필드', 44.25407, -121.14996, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RDU', 'Raleigh-Durham International Airport', '롤리 더럼 국제공항', 35.87764, -78.78747, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RFD', 'Chicago Rockford International Airport', '시카고 락퍼드 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RHI', 'Rhinelander Oneida County Airport', '라인랜더 오네이다 카운티 공항', 45.63119, -89.46745, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RIC', 'Richmond International Airport', '리치몬드 국제공항', 37.50517, -77.31967, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RIW', 'Riverton Regional Airport', '센트럴 와이오밍 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RKS', 'Rock Springs Southwest Wyoming Regional Airport', '록 스프링스 스위트워터 카운티 공항', 41.59422, -109.06519, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RNO', 'Reno-Tahoe International Airport', '리노 타호 국제공항', 39.49858, -119.76806, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ROA', 'Roanoke-Blacksburg Regional Airport', '로어노크 블랙스버그 지역공항', 37.32547, -79.97543, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ROC', 'Frederick Douglass Greater Rochester International Airport', '그레이터 로체스터 국제공항', 43.11887, -77.67238, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('ROW', 'Roswell International Air Center', '로스웰 국제 항공 센터', 33.30156, -104.53056, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RST', 'Rochester International Airport', '로체스터 국제공항', 43.90883, -92.49799, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('RSW', 'Fort Myers Southwest Florida International Airport', '사우스웨스트 플로리다 국제공항', 26.53617, -81.75517, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SAF', 'Santa Fe Regional Airport', '산타페 공항', 35.61678, -106.08814, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SAN', 'San Diego International Airport', '샌디에이고 국제공항', 32.73356, -117.18966, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SAT', 'San Antonio International Airport', '샌 안토니오 국제공항', 29.53369, -98.46978, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SAV', 'Savannah/Hilton Head International Airport', '사바나/힐튼헤드 국제공항', 32.12758, -81.20214, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SBA', 'Santa Barbara Airport', '산타바바라 공항', 34.42621, -119.84037, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SBN', 'South Bend International Airport', '사우스 벤드 국제공항', 41.70895, -86.31847, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SBP', 'San Luis Obispo County Regional Airport', '산 루이스 오비스포 카운티 지역공항', 35.23706, -120.64239, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SBY', 'Salisbury-Ocean City Wicomico Regional Airport', '솔즈베리 오션시티 위코미코 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SCC', 'Deadhorse Airport', '데드호스 공항', 70.19476, -148.46516, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SCE', 'State College Pennsylvania University Park Airport', '스테이트 칼리지 지역공항', 40.85121, -77.8463, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SCK', 'Stockton Metropolitan Airport', '스톡턴 메트로폴리탄 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SDF', 'Louisville Muhammad Ali International Airport', '루이빌 국제공항', 38.17439, -85.736, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SEA', 'Seattle-Tacoma International Airport', '시애틀 타코마 국제공항', 47.44898, -122.30931, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SFB', 'Orlando Sanford International Airport', '올랜도 샌포드 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SFO', 'San Francisco International Airport', '샌프란시스코 국제공항', 37.619, -122.37484, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SGF', 'Springfield-Branson National Airport', '스프링필드 브랜슨 내셔널 공항', 37.24433, -93.38686, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SGU', 'St George Regional Airport', '세인트 조지 공항', 37.09058, -113.59306, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SHD', 'Shenandoah Valley Regional Airport', '셰넌도어 밸리 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SHR', 'Sheridan County Airport', '셰리든 카운티 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SHV', 'Shreveport Regional Airport', '슈리브포트 공항', 32.44663, -93.8256, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SIT', 'Sitka Rocky Gutierrez Airport', '싯카 록키 구티에레스 공항', 57.04714, -135.3616, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SJC', 'San Jose Mineta International Airport', '산호세 국제공항', 37.36186, -121.92901, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SJT', 'San Angelo Regional Airport', '샌앤젤로 지역공항', 31.35775, -100.49631, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SLC', 'Salt Lake City International Airport', '솔트레이크시티 국제공항', 40.78839, -111.97777, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SLN', 'Salina Regional Airport', '살리나 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SMF', 'Sacramento International Airport', '새크라멘토 국제공항', 38.69542, -121.59077, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SMX', 'Santa Maria Public Airport', '산타 마리아 퍼블릭 공항', 34.89925, -120.45758, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SNA', 'John Wayne Orange County Airport', '존 웨인 공항', 33.67566, -117.86822, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SPI', 'Abraham Lincoln Capital Airport', '에이브러햄 링컨 캐피털 공항', 39.84395, -89.67762, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SPS', 'Wichita Falls Regional Airport', '위치타 폴스 공항', 33.9888, -98.49189, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SRQ', 'Sarasota Bradenton International Airport', '새러소타 브레이든턴 국제공항', 27.39533, -82.55411, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('STC', 'St Cloud Regional Airport', '세인트 클라우드 공항', 45.54532, -94.05834, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('STL', 'St Louis Lambert International Airport', '램버트 세인트루이스 국제공항', 38.74769, -90.35999, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('STS', 'Charles M Schulz - Sonoma County Airport', '찰스 M. 슐츠 소노마 카운티 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SUN', 'Sun Valley Friedman Memorial Airport', '프리드먼 메모리얼 공항', 43.50484, -114.29659, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SUX', 'Sioux Gateway Airport', '수 게이트웨이 공항', 42.4026, -96.38437, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SWF', 'New York Stewart International Airport', '스튜어트 국제공항', 41.50409, -74.10484, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SWO', 'Stillwater Regional Airport', '스틸워터 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('SYR', 'Syracuse Hancock International Airport', '시러큐스 핸콕 국제공항', 43.11119, -76.10631, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TBN', 'Waynesville-St. Robert Regional Airport', '웨인스빌 세인트. 로버트 지역공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TLH', 'Tallahassee International Airport', '탤러해시 국제공항', 30.39653, -84.35033, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TOL', 'Eugene F. Kranz Toledo Express Airport', '톨레도 익스프레스 공항', 41.58681, -83.80783, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TPA', 'Tampa International Airport', '탬파 국제공항', 27.97547, -82.53325, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TRI', 'Tri-Cities Airport', '트라이 시티스 공항', 36.47521, -82.40742, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TTN', 'Trenton-Mercer Airport', '트렌턴 머서 공항', 40.27669, -74.81347, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TUL', 'Tulsa International Airport', '털사 국제공항', 36.19837, -95.88824, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TUS', 'Tucson International Airport', '투손 국제공항', 32.11608, -110.94103, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TVC', 'Cherry Capital Airport', '체리 캐피탈 공항', 44.74144, -85.58224, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TWF', 'Magic Valley Regional Airport', '매직 밸리 지역 공항', 42.4818, -114.48774, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TXK', 'Texarkana Regional Airport', '텍사캐나 지역공항', 33.45371, -93.99102, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TYR', 'Tyler Pounds Regional Airport', '타일러 파운즈 공항', 32.35414, -95.40239, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('TYS', 'Knoxville McGhee Tyson Airport', '맥기 타이슨 공항', 35.81249, -83.99286, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('UIN', 'Quincy Regional Airport', '퀸시 지역 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('USA', 'Concord Regional Airport', '콩코드 지역공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('VCT', 'Victoria Regional Airport', '빅토리아 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('VEL', 'Vernal Regional Airport', '버널 공항', 40.4409, -109.50992, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('VLD', 'Valdosta Regional Airport', '발도스타 공항', 30.7825, -83.27672, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('VPS', 'Destin-Fort Walton Beach International Airport', '데스틴 포트 월튼 비치 공항', 30.48325, -86.5254, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('WRG', 'Wrangell Sea Plane Base', '랭겔 수상비행장', 56.48433, -132.36982, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('WYS', 'Yellowstone Airport', '옐로스톤 공항', 44.6884, -111.11764, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('XNA', 'Fayetteville Northwest Arkansas National Airport', '노스웨스트 아칸소 공항', 36.28187, -94.30681, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('XWA', 'Williston Basin International Airport', '윌리스턴 베이슨 국제공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('YAK', 'Yakutat Airport', '야쿠타트 공항', 59.50336, -139.66023, 0);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('YKM', 'Yakima Air Terminal', '야키마 에어 터미널', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('YNG', 'Youngstown-Warren Regional Airport', '영스타운 워렌 공항', 0.0, 0.0, 1);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, LATITUDE, LONGITUDE, disabled) VALUES('YUM', 'Yuma International Airport', '유마 국제공항', 32.65658, -114.60597, 0);
