INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ABE', 'Allentown Lehigh Valley International Airport', '리하이 밸리 국제공항', 14.6501, 4.8432);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ABI', 'Abilene Regional Airport', '애빌린 지역 공항', 13.9008, 3.7305);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ABQ', 'Albuquerque International Sunport Airport', '앨버커키 국제 선포트 공항', 13.2325, 5.4193);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ABR', 'Aberdeen Regional Airport', '애버딘 지역 공항', 14.6824, 4.2280);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ABY', 'Southwest Georgia Regional Airport', '사우스웨스트 조지아 지역 공항', 12.6657, 3.6849);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ACK', 'Nantucket Memorial Airport', '낸터컷 메모리얼 공항', 16.3508, 7.2575);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ACT', 'Waco Regional Airport', '웨이코 지역 공항', 12.7161, 3.6106);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ACV', 'Arcata-Eureka Airport', '아르카타-유레카 공항', 12.5198, 5.6953);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ACY', 'Atlantic City International Airport', '애틀랜틱시티 국제공항', 11.5805, 5.0006);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ADK', 'Adak Island Naval Airport', '아다크 섬 해군 공항', 9.4391, 5.1889);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ADQ', 'Kodiak Benny Benson State Airport', '코디악 공항', 8.9274, 3.2980);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AEX', 'Alexandria International Airport', '알렉산드리아 국제공항', 16.2111, 3.7938);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AGS', 'Augusta Regional Airport', '오거스타 공항앳 부시 필드', 16.1520, 5.0519);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AKN', 'King Salmon Airport', '킹 새먼 공항', 7.4474, 3.6071);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ALB', 'Albany International Airport', '올버니 국제공항', 14.5282, 4.3099);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ALO', 'Waterloo Regional Airport', '워털루 공항', 12.7625, 4.2891);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ALS', 'San Luis Valley Regional Airport', '샌루이스밸리 공항', 16.1848, 4.5285);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ALW', 'Walla Walla Regional Airport', '왈라왈라 공항', 7.4124, 3.9346);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AMA', 'Rick Husband Amarillo International Airport', '릭 허드슨 애머릴로 국제공항', 14.5381, 5.0972);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ANC', 'Ted Stevens Anchorage International Airport', '테드 스티븐스 앵커리지 국제공항', 14.2758, 4.5993);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('APN', 'Alpena County Regional Airport', '앨피너 카운티 공항', 11.7678, 4.4854);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ART', 'Watertown International Airport', '워터타운 국제공항', 14.7317, 4.7688);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ASE', 'Aspen/Pitkin County Airport', '아스펜 핏킨 카운티 공항', 20.5926, 4.3465);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ATL', 'Atlanta Hartsfield-Jackson International Airport', '하츠필드 잭슨 애틀랜타 국제공항', 15.6268, 8.2068);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ATW', 'Appleton International Airport', '애플턴 국제공항', 16.2036, 5.3269);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ATY', 'Watertown Airport', '워터타운 지역공항', 14.2830, 4.5762);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AUS', 'Austin-Bergstrom International Airport', '오스틴 버그스트롬 국제공항', 13.7925, 6.8184);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AVL', 'Asheville Regional Airport', '애슈빌 공항', 16.3821, 5.5790);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AVP', 'Wilkes-Barre/Scranton International Airport', '윌크스배러/스크랜턴 국제공항', 16.1189, 4.3383);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AZA', 'Phoenix Mesa Gateway Airport', '피닉스메사 게이트웨이 공항', 12.9627, 6.5553);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('AZO', 'Kalamazoo Battle Creek International Airport', '캘러머주/배틀크릭 국제공항', 17.0290, 3.7071);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BDL', 'Hartford Bradley International Airport', '브래들리 국제공항', 13.3056, 5.3779);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BET', 'Bethel Airport', '베델 공항', 8.9907, 3.7318);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BFF', 'Scottsbluff Western Nebraska Regional Airport', '웨스턴 네브래스카 리저널 공항', 16.7119, 3.8233);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BFL', 'Bakersfield Meadows Field Airport', '메도우즈 필드 공항', 15.5754, 4.5401);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BFM', 'Mobile International Airport', '모빌 다운타운 공항', 12.9576, 9.3383);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BGM', 'Greater Binghamton Airport', '그레이터 빙엄턴 공항', 15.0448, 3.6282);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BGR', 'Bangor International Airport', '뱅거 국제공항', 17.1811, 5.3469);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BHM', 'Birmingham-Shuttlesworth International Airport', '버밍엄 셔틀스워스 국제공항', 14.8597, 4.2434);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BIH', 'Bishop Regional Airport', '이스턴 시에라 공항', 14.3548, 4.4242);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BIL', 'Billings Logan International Airport', '빌링스 로건 국제공항', 14.3430, 4.0729);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BIS', 'Bismarck Airport', '비스마르크 공항', 16.2790, 4.5062);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BJI', 'Bemidji Regional Airport', '베미지 지역공항', 12.5217, 4.3406);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BKG', 'Branson Airport', '브랜슨 공항', 10.3864, 6.8103);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BLI', 'Bellingham International Airport', '벨링햄 국제공항', 12.0792, 4.9585);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BLV', 'St Louis MidAmerica Airport', '미드아메리카 세인트루이스 공항', 11.1925, 6.0182);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BMI', 'Bloomington Central Illinois Regional Airport', '센트럴 일리노이 공항', 13.9101, 4.3394);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BNA', 'Nashville International Airport', '내슈빌 국제공항', 13.3756, 6.5737);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BOI', 'Boise Airport', '보이시 공항', 13.7953, 4.0259);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BOS', 'Boston Logan International Airport', '로건 국제공항', 18.8257, 7.9149);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BPT', 'Jack Brooks Regional Airport', '잭 브룩스 공항', 15.1179, 4.4155);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BQK', 'Brunswick Golden Isles Airport', '브런즈윅 골든 아일즈 공항', 14.7490, 3.6524);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BRD', 'Brainerd Lakes Regional Airport', '브레이너드 레이크 공항', 13.4610, 4.1238);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BRO', 'Brownsville South Padre Island International Airport', '사우스 파드레 아일랜드 국제공항', 14.2635, 4.7746);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BRW', 'Barrow Wiley Post/Will Rogers Memorial Airport', '와일리 포스트 윌 로저스 메모리얼 공항', 8.1350, 4.2613);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BTM', 'Butte Bert Mooney Airport', '버트 무니 공항', 15.5097, 3.3676);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BTR', 'Baton Rouge Metropolitan Airport', '배턴루지 메트로폴리탄 공항', 15.2388, 4.4041);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BTV', 'Burlington International Airport', '벌링턴 국제공항', 18.2857, 5.2903);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BUF', 'Buffalo Niagara International Airport', '버팔로 나이아가라 국제공항', 14.2259, 4.5023);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BUR', 'Hollywood Burbank Airport', '밥 호프 공항', 14.1220, 3.4166);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BWI', 'Baltimore/Washington International Airport', '볼티모어/워싱턴 인터내셔널 서굿 마샬 공항', 13.3922, 5.5667);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('BZN', 'Bozeman Yellowstone International Airport', '보즈먼 옐로스톤 국제공항', 16.1861, 5.5949);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CAE', 'Columbia Metropolitan Airport', '콜럼비아 메트로폴리탄 공항', 15.9607, 4.7703);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CAK', 'Akron-Canton Airport', '애크런 캔턴 공항', 17.3495, 5.5378);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CDB', 'Cold Bay Airport', '콜드 베이 공항', 8.6871, 3.4345);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CDC', 'Cedar City Regional Airport', '시더 시티 공항', 14.8939, 3.1507);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CDV', 'Cordova Mudhole Smith Airport', '멀 K. 스미스 공항', 9.9885, 4.0226);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CGI', 'Cape Girardeau Regional Airport', '케이프 지라도 공항', 16.1161, 4.4995);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CHA', 'Chattanooga Metropolitan Airport', '채터누가 메트로폴피탄 공항', 15.6340, 5.3867);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CHO', 'Charlottesville Albemarle Airport', '샬러츠빌 앨버말 공항', 16.2963, 4.5552);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CHS', 'Charleston International Airport', '찰스턴 국제공항', 14.9242, 6.7986);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CID', 'Cedar Rapids Eastern Iowa Airport', '이스턴 아이오와 공항', 15.2012, 6.5256);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CIU', 'Chippewa County International Airport', '치페와 카운티 국제공항', 17.0975, 3.9619);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CKB', 'North Central West Virginia Airport', '노스 센트럴 웨스트 버지니아 공항', 15.3821, 3.7145);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CLE', 'Cleveland Hopkins International Airport', '클리블랜드 홉킨스 국제공항', 15.0154, 7.4014);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CLL', 'Easterwood Airport', '이스터우드 공항', 12.3936, 4.5951);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CLT', 'Charlotte Douglas International Airport', '샬럿 더글러스 국제공항', 21.1756, 11.9997);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CMH', 'John Glenn Columbus International Airport', '존 글렌 콜럼버스 국제공항', 14.2570, 5.9701);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CMI', 'University of Illinois - Willard Airport', '일리노이 대학교 윌러드 공항', 13.1991, 4.8111);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CMX', 'Hancock Houghton County Memorial Airport', '휴튼 카운티 메모리얼 공항', 17.0542, 4.2899);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CNY', 'Moab Canyonlands Field', '캐니언랜즈 필드', 16.8818, 4.2402);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('COD', 'Cody Yellowstone Regional Airport', '옐로스톤 공항', 18.8927, 3.9328);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('COS', 'Colorado Springs Airport', '콜로라도 스프링스 공항', 19.3317, 6.8348);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('COU', 'Columbia Regional Airport', '콜럼비아 공항', 17.4524, 4.6257);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CPR', 'Casper/Natrona County International Airport', '캐스퍼 내트로나 카운티 국제공항', 17.7487, 3.8535);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CRP', 'Corpus Christi International Airport', '코퍼스 크리스티 국제공항', 13.8088, 4.6069);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CRW', 'West Virginia International Yeager Airport', '예거 공항', 17.2610, 3.9836);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CSG', 'Columbus Airport', '콜럼버스 공항', 16.6588, 3.7514);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CVG', 'Cincinnati/Northern Kentucky International Airport', '신시내티/노던 켄터키 국제공항', 15.2410, 6.3778);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CWA', 'Central Wisconsin Airport', '센트럴 위스콘신 공항', 15.6043, 4.0058);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('CYS', 'Cheyenne Regional Airport', '샤이엔 지역공항', 15.5684, 3.3001);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DAB', 'Daytona Beach International Airport', '데이토나 비치 국제공항', 14.6441, 3.8439);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DAL', 'Dallas Love Field', '댈러스 러브 필드', 11.7811, 5.3329);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DAY', 'Dayton International Airport', '데이턴 국제공항', 16.6263, 5.3525);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DBQ', 'Dubuque Regional Airport', '더뷰크 공항', 14.9123, 4.7232);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DDC', 'Dodge City Regional Airport', '닷지 시티 공항', 15.8782, 3.5176);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DEC', 'Decatur Airport', '디케 이터 공항', 12.0284, 4.2727);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DEN', 'Denver International Airport', '덴버 국제공항', 17.3506, 9.0308);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DFW', 'Dallas Fort Worth International Airport', '댈러스/포트워스 국제공항', 18.9538, 11.9419);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DHN', 'Dothan Regional Airport', '도탄 공항', 16.7079, 3.6591);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DIK', 'Dickinson Theodore Roosevelt Regional Airport', '디킨슨 시어도어 루즈벨트 공항', 20.8116, 5.4476);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DLG', 'Dillingham Airport', '딜링햄 공항', 7.8688, 3.6831);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DLH', 'Duluth International Airport', '덜루스 국제공항', 17.2552, 5.3002);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DRO', 'Durango-La Plata County Airport', '두랑고 라플라타 카운티 공항', 19.3146, 4.9915);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DRT', 'Del Rio International Airport', '델 리오 국제공항', 14.2737, 3.2219);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DSM', 'Des Moines International Airport', '디모인 국제공항', 14.5694, 5.7454);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DTW', 'Detroit Metropolitan Airport', '디트로이트 메트로폴리탄 웨인 카운티 공항', 17.5697, 8.9755);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DUT', 'Dutch Harbor Emergency Field', '어널래스카 공항', 4.7632, 2.7811);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('DVL', 'Devils Lake Regional Airport', '데블스 레이크 리저널 공항', 18.9807, 4.9415);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EAR', 'Kearney Regional Airport', '카니 공항', 16.9122, 4.1461);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EAT', 'Pangborn Memorial Airport', '팽본 메모리얼 공항', 8.2646, 4.6579);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EAU', 'Chippewa Valley Regional Airport', '치페와 밸리 공항', 15.7446, 3.6001);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ECP', 'Panama City Northwest Florida Beaches International Airport', '노스웨스트 플로리다 비치 국제공항', 11.9590, 4.1839);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EGE', 'Vail Eagle County Regional Airport', '이글 카운티 공항', 18.6658, 6.4947);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EKO', 'Elko Regional Airport', '엘코 공항', 13.4129, 4.3400);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ELM', 'Elmira Corning Regional Airport', '엘미라 코닝 지역 공항', 15.4849, 4.3264);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ELP', 'El Paso International Airport', '엘패소 국제공항', 14.1223, 3.8710);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ERI', 'Erie International Airport', '이리 국제공항', 16.9926, 3.7632);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ESC', 'Delta County Airport', '델타 카운티 공항', 13.0915, 4.0105);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EUG', 'Eugene Airport', '유진 공항', 13.8923, 4.8306);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EVV', 'Evansville Regional Airport', '에반스빌 공항', 17.9008, 4.6023);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EWN', 'New Bern Coastal Carolina Regional Airport', '코스탈 캐롤라이나 공항', 15.5445, 3.5470);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EWR', 'New York Newark Liberty International Airport', '뉴어크 리버티 국제공항', 23.3664, 10.7752);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('EYW', 'Key West International Airport', '키웨스트 국제공항', 12.6588, 7.4945);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FAI', 'Fairbanks International Airport', '페어뱅크스 국제공항', 13.3971, 3.5488);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FAR', 'Fargo Hector International Airport', '헥터 국제공항', 17.8417, 5.6688);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FAT', 'Fresno Yosemite International Airport', '프레즈노 요세미티 국제공항', 13.9126, 5.2662);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FAY', 'Fayetteville Regional Airport', '페이엇빌 리저널 공항', 16.0802, 4.3185);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FCA', 'Kalispell Glacier Park International Airport', '글레이셔 파크 국제공항', 16.2551, 4.5824);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FLG', 'Grand Canyon Pulliam Airport', '플래그스태프 풀리엄 공항', 19.4796, 4.0803);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FLL', 'Fort Lauderdale-Hollywood International Airport', '포트로더데일 할리우드 국제공항', 16.8458, 7.2348);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FLO', 'Florence Regional Airport', '피렌체 공항', 18.8486, 7.1438);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FNT', 'Flint Bishop International Airport', '비숍 국제공항', 14.8913, 5.4579);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FOD', 'Fort Dodge Regional Airport', '포트닷지 공항', 12.3367, 4.2815);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FSD', 'Sioux Falls Regional Airport', '수폴스 지역공항', 17.5971, 5.6951);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FSM', 'Fort Smith Regional Airport', '포트 스미스 공항', 14.3371, 3.8478);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('FWA', 'Fort Wayne International Airport', '포트 웨인 국제공항', 16.0710, 6.0127);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GCC', 'Northeast Wyoming Regional Airport', '질레트 캠벨 카운티 공항', 17.8068, 5.1864);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GCK', 'Garden City Regional Airport', '가든 시티 공항', 12.7190, 3.8904);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GEG', 'Spokane International Airport', '스포캔 국제공항', 14.1561, 4.2035);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GFK', 'Grand Forks International Airport', '그랜드 폭스 국제공항', 15.7765, 4.4261);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GGG', 'East Texas Regional Airport', '이스트 텍사스 공항', 14.2806, 4.4718);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GJT', 'Grand Junction Regional Airport', '워커 필드 공항', 16.5587, 3.8400);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GNV', 'Gainesville Regional Airport', '게인즈빌 공항', 13.5049, 4.2493);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GPT', 'Gulfport-Biloxi International Airport', '걸프포트 빌럭시 국제공항', 14.5581, 4.5675);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GRB', 'Green Bay Austin Straubel International Airport', '오스틴 스트라우벨 국제공항', 14.7267, 4.1333);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GRI', 'Central Nebraska Regional Airport', '센트럴 네브래스카 공항', 12.9441, 5.0793);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GRK', 'Killeen/Fort Hood Regional Airport', '킬린 포트 후드 공항', 17.0802, 4.3229);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GRR', 'Grand Rapids Gerald R Ford International Airport', '제럴드 R. 포드 국제공항', 15.6345, 6.1162);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GSO', 'Piedmont Triad International Airport', '피드몬트 트라이어드 국제공항', 17.6416, 5.7740);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GSP', 'Greenville-Spartanburg International Airport', '그린빌 스파르탄버그 국제공항', 16.2404, 4.1204);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GST', 'Gustavus Airport', '구스타프 공항', 11.5841, 6.2083);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GTF', 'Great Falls International Airport', '그레이트 폴스 국제공항', 13.5010, 4.1652);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GTR', 'Golden Triangle Regional Airport', '골든 트라이앵글 공항', 14.3373, 3.4304);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('GUC', 'Gunnison Crested Butte Regional Airport', '거니슨 크레스티드 뷰트 공항', 18.6227, 3.7684);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HDN', 'Yampa Valley Regional Airport', '얌파 밸리 공항', 20.2002, 4.9788);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HGR', 'Hagerstown Regional Airport', '헤이거즈타운 지역공항', 9.0657, 5.5725);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HHH', 'Hilton Head Island Airport', '힐튼 헤드 공항', 17.8982, 8.1676);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HIB', 'Range Regional Airport', '레인지 공항', 13.5919, 3.3132);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HLN', 'Helena Regional Airport', '헬레나 공항', 16.6808, 3.4043);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HNL', 'Honolulu Daniel K Inouye International Airport', '호놀룰루 국제공항', 15.1254, 7.0521);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HOB', 'Lea County Regional Airport', '레아 카운티 공항', 12.7012, 4.6186);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HOU', 'Houston William P. Hobby Airport', '윌리엄 P. 하비 공항', 10.9622, 5.6424);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HPN', 'Westchester County Airport', '웨스트체스터 카운티 공항', 15.9324, 5.1740);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HRL', 'Harlingen Valley International Airport', '밸리 국제공항', 12.4564, 3.0377);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HSV', 'Huntsville International Airport', '헌츠빌 국제공항', 15.6652, 5.3467);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HTS', 'Huntington Tri-State Airport', '트라이 스테이트 공항', 12.7832, 4.9209);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HVN', 'Tweed New Haven Airport', '트위드 뉴 헤이븐 공항', 12.9647, 3.9667);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HYA', 'Cape Cod Gateway Airport', '반스터블 뮤니시펄 공항', 10.2624, 4.1574);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('HYS', 'Hays Regional Airport', '헤이스 공항', 13.8339, 4.3004);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('IAD', 'Washington Dulles International Airport', '워싱턴 덜레스 국제공항', 20.4980, 6.4967);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('IAG', 'Niagara Falls International Airport', '나이아가라 폭포 국제공항', 13.6358, 7.2034);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('IAH', 'Houston George Bush Intercontinental Airport', '조지 부시 인터컨티넨털 공항', 18.8912, 8.5316);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ICT', 'Wichita Dwight D Eisenhower National Airport', '위치타 드와이트 D. 아이젠하워 내셔널 공항', 14.0391, 4.6476);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('IDA', 'Idaho Falls Regional Airport', '아이다호폴스 공항', 15.8985, 4.3834);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ILG', 'Wilmington New Castle Airport', '윌밍턴 공항', 12.1481, 9.7798);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ILM', 'Wilmington International Airport', '윌밍턴 국제공항', 15.3053, 4.9334);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('IMT', 'Iron Mountain Ford Airport', '포드 공항', 11.6661, 3.9480);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('IND', 'Indianapolis International Airport', '인디애나폴리스 국제공항', 14.4258, 6.1921);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('INL', 'Falls International Airport', '폴스 국제공항', 12.5431, 3.7192);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('IPT', 'Williamsport Regional Airport', '윌리엄스포트 공항', 13.6223, 6.1267);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ISP', 'Long Island MacArthur Airport', '롱 아일랜드 맥아더 공항', 12.1726, 5.0585);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ITH', 'Ithaca Tompkins International Airport', '이타카 톰킨스 공항', 18.8579, 4.5151);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ITO', 'Hilo International Airport', '힐로 국제공항', 9.1152, 5.2291);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JAC', 'Jackson Hole Airport', '잭슨홀 공항', 19.6896, 4.7157);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JAN', 'Jackson-Medgar Wiley Evers International Airport', '잭슨 에버스 국제공항', 14.3932, 4.8583);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JAX', 'Jacksonville International Airport', '잭슨빌 국제공항', 13.6047, 5.6522);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JFK', 'New York John F Kennedy International Airport', '존 F. 케네디 국제공항', 24.2195, 9.9872);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JHM', 'Kapalua Airport', '카팔루아 공항', 3.3274, 2.1911);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JLN', 'Joplin Regional Airport', '조플린 공항', 17.0187, 4.8920);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JMS', 'Jamestown Regional Airport', '제임스타운 공항', 14.6316, 4.1654);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JNU', 'Juneau International Airport', '주노 국제공항', 14.1675, 4.1743);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('JST', 'John Murtha Johnstown-Cambria County Airport', '존 머사 존스타운 캄브리아 카운티 공항', 15.5495, 3.7478);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('KOA', 'Kona International Airport', '케아홀 코나 국제공항', 11.1554, 5.7064);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('KTN', 'Ketchikan International Airport', '케치칸 국제공항', 12.2623, 4.4165);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LAN', 'Lansing Capital Region International Airport', '캐피털 리전 국제공항', 16.2955, 3.9572);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LAR', 'Laramie Regional Airport', '래러미 공항', 17.4101, 4.4037);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LAS', 'Las Vegas Harry Reid International Airport', '해리 리드 국제공항', 15.1571, 7.1038);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LAW', 'Lawton/Fort Sill Regional Airport', '로턴 포트실 공항', 15.2737, 3.3264);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LAX', 'Los Angeles International Airport', '로스 앤젤레스 국제공항', 16.7695, 10.6302);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LBB', 'Lubbock Preston Smith International Airport', '러벅 프레스턴 스미스 국제공항', 14.4208, 4.2775);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LBE', 'Arnold Palmer Regional Airport', '아놀드 파머 공항', 12.1096, 6.4475);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LBF', 'North Platte Regional Airport', '노스플랫 지역공항', 16.5061, 4.9672);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LBL', 'Liberal Municipal Airport', '리버럴 미드 아메리카 공항', 13.8658, 4.4733);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LCH', 'Lake Charles Regional Airport', '레이크 찰스 공항', 13.4986, 4.9155);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LCK', 'Columbus Rickenbacker International Airport', '리켄베커 국제공항', 11.7081, 5.9516);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LEX', 'Lexington Blue Grass Airport', '블루 그래스 공항', 16.4882, 5.3051);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LFT', 'Lafayette Regional Airport', '라파예트 공항', 16.8180, 5.7037);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LGA', 'New York LaGuardia Airport', '라과디아 공항', 23.7077, 8.4499);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LGB', 'Long Beach Airport', '롱비치 공항', 12.2236, 4.3135);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LIH', 'Lihue Airport', '리후에 공항', 9.6266, 6.2247);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LIT', 'Little Rock Bill and Hillary Clinton National Airport', '클린턴 내셔널 공항', 14.5624, 5.6046);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LNK', 'Lincoln Airport', '링컨 공항', 17.2194, 4.4061);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LNY', 'Lanai Airport', '라나이 공항', 5.4396, 1.7307);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LRD', 'Laredo International Airport', '라레도 국제공항', 15.1827, 4.1982);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LSE', 'La Crosse Regional Airport', '라크로스 공항', 13.8021, 3.5488);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LWB', 'Lewisburg Greenbrier Valley Airport', '그린브리어 밸리 공항', 13.2656, 3.6367);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LWS', 'Lewiston Nez Perce County Regional Airport', '루이스턴 네즈 퍼스 카운티 공항', 11.9360, 4.4446);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('LYH', 'Lynchburg Regional Airport', '린치버그 리저널 공항', 19.1738, 5.2410);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MAF', 'Midland International Airport', '미들랜드 국제 항공 우주 항구', 13.3930, 4.1062);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MBS', 'MBS International Airport', 'MBS 국제공항', 16.8831, 4.2624);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MCI', 'Kansas City International Airport', '캔자스시티 국제공항', 12.8219, 5.0895);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MCO', 'Orlando International Airport', '올랜도 국제공항', 15.7211, 9.5614);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MCW', 'Mason City Municipal Airport', '메이슨 시티 공항', 15.0259, 4.3695);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MDT', 'Harrisburg International Airport', '해리스버그 국제공항', 15.9554, 5.7854);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MDW', 'Chicago Midway International Airport', '미드웨이 국제공항', 11.6324, 5.7127);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MEI', 'Meridian Regional Airport', '메리디언 지역공항', 13.6948, 4.4885);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MEM', 'Memphis International Airport', '멤피스 국제공항', 14.8421, 5.4624);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MFE', 'McAllen International Airport', '매캘런 밀러 국제공항', 13.4182, 4.6472);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MFR', 'Rogue Valley International-Medford Airport', '로그 밸리 국제-메드퍼드 공항', 13.1107, 4.4639);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MGM', 'Montgomery Regional Airport', '몽고메리 지역공항', 16.1180, 4.0161);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MHK', 'Manhattan Regional Airport', '맨해튼 공항', 13.9966, 4.0094);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MHT', 'Manchester-Boston Regional Airport', '맨체스터 보스턴 공항', 13.8254, 4.6371);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MIA', 'Miami International Airport', '마이애미 국제공항', 18.7506, 8.4767);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MKE', 'Milwaukee Mitchell International Airport', '밀워키 미첼 국제공항', 14.0175, 5.2365);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MKG', 'Muskegon County Airport', '머스키건 카운티 공항', 14.3511, 4.3900);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MKK', 'Molokai Airport', '몰로카이 공항', 3.8551, 2.0395);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MLB', 'Melbourne Orlando(US) International Airport ', '멜버른 올랜도(US) 국제공항', 14.3924, 4.1639);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MLI', 'Quad Cities International Airport', '쿼드 시티 국제공항', 15.5108, 5.3334);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MLU', 'Monroe Regional Airport', '먼로 공항', 14.2933, 4.4913);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MMH', 'Mammoth Lakes Mammoth Yosemite Airport', '맘모스 요세미티 공항', 17.5961, 3.9806);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MOB', 'Mobile Regional Airport', '모빌 공항', 14.1000, 4.7541);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MOT', 'Minot International Airport', '미놋 국제공항', 16.7220, 5.4764);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MQT', 'Marquette Sawyer International Airport', '소여 국제공항', 15.8416, 4.7520);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MRY', 'Monterey Regional Airport', '몬터레이 공항', 14.7959, 3.4823);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MSN', 'Dane County Regional Airport', '데인 카운티 리저널 공항', 14.8675, 5.0621);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MSO', 'Missoula Montana Airport', '미줄라 국제공항', 15.5754, 5.6375);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MSP', 'Minneapolis St Paul International Airport', '미니애폴리스 세인트폴 국제공항', 17.9041, 6.0364);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MSY', 'New Orleans Louis Armstrong International Airport', '루이 암스트롱 뉴올리언스 국제공항', 12.2063, 5.2960);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MTJ', 'Montrose Regional Airport', '몬트로즈 공항', 17.6047, 5.5307);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MVY', 'Marthas Vineyard Airport', '마사스 빈야드 공항', 13.5437, 5.9819);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('MYR', 'Myrtle Beach International Airport', '머틀 비치 국제공항', 13.2254, 5.7099);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OAJ', 'Jacksonville Albert J Ellis Airport', '앨버트 J. 엘리스 공항', 16.8474, 3.6229);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OAK', 'Oakland San Francisco Bay Airport', '오클랜드 국제공항', 11.8359, 5.9961);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OGD', 'Ogden Regional Airport', '오그덴 힝클리 공항', 8.1036, 5.7107);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OGG', 'Kahului Airport', '카훌루이 공항', 10.5311, 7.5466);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OGS', 'Ogdensburg International Airport', '오그덴스버그 국제공항', 17.0419, 3.8734);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OKC', 'Will Rogers World Airport', '윌 로저스 월드 공항', 13.9776, 5.0444);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OMA', 'Omaha Eppley International Airport', '에플리 비행장', 14.2803, 4.4352);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OME', 'Nome Airport', '놈 공항', 9.6702, 3.5878);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ONT', 'Ontario International Airport', '온타리오 국제공항', 11.7959, 4.4415);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ORD', 'Chicago OHare International Airport', '오헤어 국제공항', 22.1382, 13.1082);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ORF', 'Norfolk International Airport', '노퍽 국제공항', 15.2164, 4.7050);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ORH', 'Worcester Regional Airport', '우스터 공항', 14.4693, 4.9046);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OTH', 'Southwest Oregon Regional Airport', '사우스웨스트 오리건 공항', 11.9753, 3.9548);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OTZ', 'Kotzebue Airport', '랄프 빈 메모리얼 공항', 8.4561, 3.8679);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('OWB', 'Owensboro-Daviess County Regional Airport', '오웬스보로 데이비스 카운티 공항', 5.9313, 6.1730);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PAE', 'Seattle Paine Field International Airport', '페인 필드 공항', 13.0557, 4.2511);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PAH', 'Barkley Regional Airport', '바클리 공항', 12.2108, 4.0745);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PBG', 'Plattsburgh International Airport', '플래츠버그 국제공항', 14.6618, 5.4286);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PBI', 'Palm Beach International Airport', '팜 비치 국제공항', 14.6465, 4.7423);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PDX', 'Portland International Airport', '포틀랜드 국제공항', 12.9716, 4.7266);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PGD', 'Punta Gorda Charlotte County Airport', '푼타고르다 샬럿카운티 공항', 11.1636, 7.2569);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PGV', 'Pitt-Greenville Airport', '피트 그린빌 공항', 19.6412, 6.1946);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PHF', 'Newport News Williamsburg International Airport', '뉴포트뉴스/윌리엄스버그 국제공항', 15.6209, 5.2319);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PHL', 'Philadelphia International Airport', '필라델피아 국제공항', 21.2281, 7.5454);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PHX', 'Phoenix Sky Harbor International Airport', '피닉스 스카이 하버 국제공항', 14.6177, 7.2696);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PIA', 'Peoria General Wayne A. Downing International Airport', '제너럴 웨인 A. 다우닝 피오리아 국제공항', 15.4861, 4.7246);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PIB', 'Hattiesburg-Laurel Regional Airport', '해티즈버그 로렐 공항', 14.6097, 4.3034);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PIE', 'Tampa St Pete-Clearwater International Airport', '세인트피트 클리어워터 국제공항', 12.8042, 6.9391);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PIH', 'Pocatello Regional Airport', '포커텔로 공항', 12.7091, 2.9943);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PIR', 'Pierre Regional Airport', '피에르 공항', 12.7792, 4.0437);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PIT', 'Pittsburgh International Airport', '피츠버그 국제공항', 14.4572, 5.8473);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PLN', 'Pellston Regional Airport', '펠스턴 리저널 공항', 12.5874, 5.3785);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PNS', 'Pensacola International Airport', '펜사콜라 국제공항', 13.1414, 4.5925);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PQI', 'Presque Isle International Airport', '프레스크 아일 노던 메인 공항', 22.7788, 5.4841);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PRC', 'Prescott Regional Airport', '어니스트 에이 러브 필드', 16.8483, 3.2028);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PSC', 'Pasco Tri-Cities Airport', '트라이 시티 공항', 14.1662, 5.1507);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PSG', 'Petersburg James A Johnson Airport', '피터스버그 제임스 A. 존슨 공항', 9.6443, 3.8849);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PSM', 'Portsmouth Pease International Airport', '피스 포츠머스 국제공항', 13.0468, 5.9646);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PSP', 'Palm Springs International Airport', '팜스프링스 국제공항', 14.1274, 5.6884);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PUB', 'Pueblo Airport', '푸에블로 메모리얼 공항', 15.8815, 4.1125);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PUW', 'Pullman Moscow Regional Airport', '풀만 모스크바 공항', 8.4438, 4.9830);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PVD', 'Rhode Island T F Green International Airport', '시어도어 프랜시스 그린 스테이트 공항', 13.7669, 4.8227);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PVU', 'Provo Municipal Airport', '프로보 공항', 12.1208, 5.7125);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('PWM', 'Portland International Jetport', '포틀랜드 국제공항제트포트', 15.2463, 4.6615);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RAP', 'Rapid City Regional Airport', '래피드 시티 공항', 16.5552, 6.1798);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RDD', 'Redding Regional Airport', '레딩 공항', 13.6716, 4.3835);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RDM', 'Redmond Municipal Airport', '로버츠 필드', 14.6495, 4.9689);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RDU', 'Raleigh-Durham International Airport', '롤리 더럼 국제공항', 16.9277, 5.8737);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RFD', 'Chicago Rockford International Airport', '시카고 락퍼드 국제공항', 11.0101, 6.0700);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RHI', 'Rhinelander Oneida County Airport', '라인랜더 오네이다 카운티 공항', 14.0866, 3.8558);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RIC', 'Richmond International Airport', '리치몬드 국제공항', 16.7462, 6.6139);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RIW', 'Riverton Regional Airport', '센트럴 와이오밍 공항', 16.9746, 4.0000);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RKS', 'Rock Springs Southwest Wyoming Regional Airport', '록 스프링스 스위트워터 카운티 공항', 16.1166, 3.0164);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RNO', 'Reno-Tahoe International Airport', '리노 타호 국제공항', 14.0220, 4.8418);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ROA', 'Roanoke-Blacksburg Regional Airport', '로어노크 블랙스버그 지역공항', 18.3617, 6.2814);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ROC', 'Frederick Douglass Greater Rochester International Airport', '그레이터 로체스터 국제공항', 15.4541, 6.0582);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('ROW', 'Roswell International Air Center', '로스웰 국제 항공 센터', 14.3095, 4.4484);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RST', 'Rochester International Airport', '로체스터 국제공항', 17.1812, 3.9190);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('RSW', 'Fort Myers Southwest Florida International Airport', '사우스웨스트 플로리다 국제공항', 13.7654, 5.5782);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SAF', 'Santa Fe Regional Airport', '산타페 공항', 17.8413, 4.7477);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SAN', 'San Diego International Airport', '샌디에이고 국제공항', 16.1530, 4.0369);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SAT', 'San Antonio International Airport', '샌 안토니오 국제공항', 12.1542, 4.2114);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SAV', 'Savannah/Hilton Head International Airport', '사바나/힐튼헤드 국제공항', 15.0451, 6.1386);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SBA', 'Santa Barbara Airport', '산타바바라 공항', 14.4683, 4.4744);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SBN', 'South Bend International Airport', '사우스 벤드 국제공항', 16.4671, 4.9813);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SBP', 'San Luis Obispo County Regional Airport', '산 루이스 오비스포 카운티 지역공항', 15.3433, 4.6051);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SBY', 'Salisbury-Ocean City Wicomico Regional Airport', '솔즈베리 오션시티 위코미코 공항', 14.8997, 5.7164);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SCC', 'Deadhorse Airport', '데드호스 공항', 9.0459, 3.6523);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SCE', 'State College Pennsylvania University Park Airport', '스테이트 칼리지 지역공항', 14.4733, 4.1049);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SCK', 'Stockton Metropolitan Airport', '스톡턴 메트로폴리탄 공항', 9.5386, 5.8739);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SDF', 'Louisville Muhammad Ali International Airport', '루이빌 국제공항', 15.3527, 6.9375);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SEA', 'Seattle-Tacoma International Airport', '시애틀 타코마 국제공항', 18.4012, 9.6090);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SFB', 'Orlando Sanford International Airport', '올랜도 샌포드 국제공항', 13.6213, 6.3516);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SFO', 'San Francisco International Airport', '샌프란시스코 국제공항', 19.7307, 7.4182);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SGF', 'Springfield-Branson National Airport', '스프링필드 브랜슨 내셔널 공항', 16.5582, 5.7669);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SGU', 'St George Regional Airport', '세인트 조지 공항', 16.8797, 3.1737);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SHD', 'Shenandoah Valley Regional Airport', '셰넌도어 밸리 공항', 14.0654, 3.9024);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SHR', 'Sheridan County Airport', '셰리든 카운티 공항', 18.7724, 4.1591);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SHV', 'Shreveport Regional Airport', '슈리브포트 공항', 14.6174, 5.4163);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SIT', 'Sitka Rocky Gutierrez Airport', '싯카 록키 구티에레스 공항', 11.6029, 4.2192);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SJC', 'San Jose Mineta International Airport', '산호세 국제공항', 12.8154, 4.3785);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SJT', 'San Angelo Regional Airport', '샌앤젤로 지역공항', 12.7012, 3.4059);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SLC', 'Salt Lake City International Airport', '솔트레이크시티 국제공항', 17.4575, 7.4453);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SLN', 'Salina Regional Airport', '살리나 공항', 16.4264, 5.2096);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SMF', 'Sacramento International Airport', '새크라멘토 국제공항', 12.2311, 4.8181);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SMX', 'Santa Maria Public Airport', '산타 마리아 퍼블릭 공항', 7.4254, 5.4648);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SNA', 'John Wayne Orange County Airport', '존 웨인 공항', 13.4429, 5.7979);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SPI', 'Abraham Lincoln Capital Airport', '에이브러햄 링컨 캐피털 공항', 13.8367, 4.1674);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SPS', 'Wichita Falls Regional Airport', '위치타 폴스 공항', 16.1314, 6.9361);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SRQ', 'Sarasota Bradenton International Airport', '새러소타 브레이든턴 국제공항', 14.1896, 5.3998);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('STC', 'St Cloud Regional Airport', '세인트 클라우드 공항', 11.3734, 8.8015);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('STL', 'St Louis Lambert International Airport', '램버트 세인트루이스 국제공항', 12.0807, 4.9746);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('STS', 'Charles M Schulz - Sonoma County Airport', '찰스 M. 슐츠 소노마 카운티 공항', 13.5728, 5.2659);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SUN', 'Sun Valley Friedman Memorial Airport', '프리드먼 메모리얼 공항', 14.9155, 2.9133);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SUX', 'Sioux Gateway Airport', '수 게이트웨이 공항', 14.4753, 4.6459);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SWF', 'New York Stewart International Airport', '스튜어트 국제공항', 15.0335, 5.8278);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SWO', 'Stillwater Regional Airport', '스틸워터 공항', 13.2421, 3.8238);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('SYR', 'Syracuse Hancock International Airport', '시러큐스 핸콕 국제공항', 17.3740, 5.0819);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TBN', 'Waynesville-St. Robert Regional Airport', '웨인스빌 세인트. 로버트 지역공항', 11.7218, 3.4247);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TLH', 'Tallahassee International Airport', '탤러해시 국제공항', 13.3089, 4.4517);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TOL', 'Eugene F. Kranz Toledo Express Airport', '톨레도 익스프레스 공항', 12.1779, 3.9975);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TPA', 'Tampa International Airport', '탬파 국제공항', 13.7445, 5.1469);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TRI', 'Tri-Cities Airport', '트라이 시티스 공항', 15.7602, 4.7266);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TTN', 'Trenton-Mercer Airport', '트렌턴 머서 공항', 15.8306, 8.0820);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TUL', 'Tulsa International Airport', '털사 국제공항', 14.8265, 4.4416);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TUS', 'Tucson International Airport', '투손 국제공항', 13.7450, 4.4287);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TVC', 'Cherry Capital Airport', '체리 캐피탈 공항', 15.8108, 5.3017);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TWF', 'Magic Valley Regional Airport', '매직 밸리 지역 공항', 12.7006, 3.0923);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TXK', 'Texarkana Regional Airport', '텍사캐나 지역공항', 13.1967, 3.4631);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TYR', 'Tyler Pounds Regional Airport', '타일러 파운즈 공항', 14.4465, 4.0839);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('TYS', 'Knoxville McGhee Tyson Airport', '맥기 타이슨 공항', 16.3312, 4.9443);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('UIN', 'Quincy Regional Airport', '퀸시 지역 공항', 14.8219, 4.0197);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('USA', 'Concord Regional Airport', '콩코드 지역공항', 11.9851, 6.2093);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('VCT', 'Victoria Regional Airport', '빅토리아 공항', 11.7802, 4.2859);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('VEL', 'Vernal Regional Airport', '버널 공항', 14.9451, 3.5248);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('VLD', 'Valdosta Regional Airport', '발도스타 공항', 14.1892, 4.2536);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('VPS', 'Destin-Fort Walton Beach International Airport', '데스틴 포트 월튼 비치 공항', 14.9489, 8.7712);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('WRG', 'Wrangell Sea Plane Base', '랭겔 수상비행장', 8.1848, 3.8397);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('WYS', 'Yellowstone Airport', '옐로스톤 공항', 12.1512, 3.8177);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('XNA', 'Fayetteville Northwest Arkansas National Airport', '노스웨스트 아칸소 공항', 15.8936, 6.2639);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('XWA', 'Williston Basin International Airport', '윌리스턴 베이슨 국제공항', 22.8546, 5.3335);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('YAK', 'Yakutat Airport', '야쿠타트 공항', 10.1282, 4.3196);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('YKM', 'Yakima Air Terminal', '야키마 에어 터미널', 6.9992, 3.9153);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('YNG', 'Youngstown-Warren Regional Airport', '영스타운 워렌 공항', 24.2195, 10.0000);
INSERT INTO airport_info(airport_code, airport_name_en, airport_name_ko, taxiout_mean, taxiin_mean) VALUES('YUM', 'Yuma International Airport', '유마 국제공항', 14.4432, 4.2022);